Update CheckmarxCLI.gitlab-ci.yml

diff --git a/CheckmarxCLI.gitlab-ci.yml b/CheckmarxCLI.gitlab-ci.yml
--- a/CheckmarxCLI.gitlab-ci.yml
+++ b/CheckmarxCLI.gitlab-ci.yml
@@ -24,17 +24,16 @@ checkmarx-scan:
   image:
     name: checkmarx/${CHECKMARX_DOCKER_IMAGE}
     entrypoint: ['']
-  script:
-    - eval "arr=(${ADDITIONAL_PARAMS})"
-    - /app/bin/cx scan create --project-name "${CI_PROJECT_NAME}" --file-source "${CI_REPOSITORY_URL}" --format json --agent "Gitlab" "${arr[@]}"
-  
-    - exitCode=$?
+  script:  
+    eval "arr=(${ADDITIONAL_PARAMS})"
+    /app/bin/cx scan create --project-name "${CI_PROJECT_NAME}" --file-source "${CI_REPOSITORY_URL}" --format json --agent "Gitlab" "${arr[@]}"
+    exitCode=$?
 
-    - echo "Program exits with code: " $exitCode
-    - if [ $exitCode -eq 0 ]
-    - then
-    - echo "Scan completed"
-    - else
-    - echo "Scan Failed"
-    - exit $exitCode
-    - fi
+    echo "Program exits with code: " $exitCode
+    if [ $exitCode -eq 0 ]
+    then
+      echo "Scan completed"
+    else
+      echo "Scan Failed"
+      exit $exitCode
+    fi
